model:
  tse_model: TFGridNet
model_args:
  tse_model:
    n_srcs: 1
    n_fft: 128
    stride: 64
    window: "hann"
    n_imics: 1
    n_layers: 6
    lstm_hidden_units: 192
    attn_n_head: 4
    attn_approx_qk_dim: 512
    emb_dim: 128
    emb_ks: 1
    emb_hs: 1
    activation: "prelu"
    eps: 1.0e-5
    spk_emb_dim: 256
    use_spk_transform: False
    spk_fuse_type: "multiply"
    joint_training: False