# loss: [SISDR]               ###SI_SNR, SDR, sisnr, CE
# loss_args:
#   loss_posi: [0,1,2]
#   loss_weight: [0.8,0.1,0.1]


model:
  tse_model: ConvTasNet
model_args:
  tse_model:
    B: 256
    H: 512
    L: 20
    N: 256
    P: 3
    R: 4
    X: 8
    spk_emb_dim: 256
    activate: relu
    causal: false
    norm: gLN
    skip_con: False
    spk_fuse_type: FiLM # "concat", "additive", "multiply", "FiLM", "None", ("concatConv" only for convtasnet)
    use_spk_transform: False
    multi_fuse: True        # Multi speaker fuse with seperation modules
    encoder_type: Multi # Multi, Deep, False
    decoder_type: Multi # Multi, Deep, False
    joint_training: False
    multi_task: False
    spksInTrain: 251    #wsj0-2mix: 101; Libri2mix-100: 251; Libri2mix-360:921